<?php

/**
 * @abstract 用户控制器
 * @author   Yxl <zccem@163.com>
 */

namespace frontend\controllers;

use common\models\Job;

class UserController extends BaseController
{

    public function init()
    {
        return parent::init(); // TODO: Change the autogenerated stub

        $this->isUser();
    }

    /**
     * @abstract 用户中心
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * 签到
     *
     * @return string
     */
    public function actionCheck()
    {
        return $this->render('check');
    }

}
