<?php
/**
 * Created by Yxl.
 * User: <zccem@163.com>.
 * Date: 2018/6/10
 * Time: 20:13
 */

namespace common\widgets\iMenu;

use Yii;
use yii\widgets\InputWidget;
use common\models\Menu;
use common\models\Conf;

class MenuList extends InputWidget
{

    public $config = array();

    public function init()
    {
        return;
    }

    public function run()
    {
        // TODO: Change the autogenerated stub
        parent::run();

        $result = static::MenuNavList($this->config[0], $this->config[1]);

        return $this->render('list', ['result' => $result]);
    }

    public function MenuNavList($pid, $language = 'cn')
    {

        $result['menu'] = Menu::findMenuNav($pid, $language);

        $confData = Conf::findByData('On', $language);

        foreach ($confData as $key => $value) {
            $result['conf'][ $value['c_key'] ] = $value['parameter'];
        }

        return $result;
    }
}