<?php
/**
 * Created by Yxl.
 * User: <zccem@163.com>.
 * Date: 2018/6/11
 * Time: 17:13
 */

namespace common\widgets\iMenu;

use Yii;
use yii\widgets\InputWidget;
use common\models\Menu;
use common\models\Conf;

class MenuAdmin extends InputWidget
{

    public $config = array();

    public function init()
    {
        return;
    }

    public function run()
    {

        // TODO: Change the autogenerated stub
        parent::run();

        $result = static::MenuNavList($this->config[0]);

        return $this->render('admin', ['result' => $result]);
    }

    /**
     * 菜单导航
     *
     * @param $pid
     * @return mixed
     */
    public static function MenuNavList($pid)
    {

        $result['menu'] = Menu::findMenuNav($pid);

        print_r($result['menu']);
        exit();

        $confData = Conf::findByData('On');

        foreach ($confData as $key => $value) {
            $result['conf'][ $value['c_key'] ] = $value['parameter'];
        }

        return $result;
    }

}