<?php
/**
 * Created by Yxl.
 * User: <zccem@163.com>.
 * Date: 2018/6/11
 * Time: 17:13
 */

namespace common\widgets\iMenu;

use Yii;
use yii\widgets\InputWidget;
use common\models\Menu;
use common\models\Conf;

class MenuAdmin extends InputWidget
{

    public $config = array();

    public function init()
    {
        return;
    }

    public function run()
    {

        // TODO: Change the autogenerated stub
        parent::run();

        $result = static::MenuNavList($this->config[0]);

        return $this->render('admin', ['result' => $result]);
    }

    /**
     * 菜单导航
     *
     * @param $pid
     * @return mixed
     */
    public static function MenuNavList($pid)
    {

        $result['menu'] = Menu::findMenuNav($pid);

        $controller = explode('/', Yii::$app->controller->id)[1] . '/' . Yii::$app->controller->action->id;

        $menuActive = Menu::findOne(['url' => $controller]);

        $open = static::recursionUp($menuActive['parent_id']);

        foreach ($result['menu'] as $key => $value) {
            if ($value['m_key'] == $open)
                $result['menu'][ $key ]['open'] = 'On';
        }

        $confData = Conf::findByData('On');

        foreach ($confData as $key => $value) {
            $result['conf'][ $value['c_key'] ] = $value['parameter'];
        }

        return $result;
    }

    public static function recursionUp($pid)
    {

        $parent = Menu::findOne(['parent_id' => $pid]);

        if (empty($parent))
            return $parent;

        static::recursionUp($parent['m_key']);

        return;
    }

}